
name: build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Commit Message
        id: get_commit
        run: echo "COMMIT_MESSAGE=${{github.event.head_commit.message}}"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go get .

      - name: Backup Running API
        run: mv api.exe api_backup.exe 

      - name: Go Build
        run: go build -o api.exe main.g
